# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4708845b08f5da9618dd803c2224e80621395d830ffebdb1528b8bde5caeee6fb39d5d8e03b16ad636ef181e98bfe1cbd16152388375843aedafa088ed65ebf

test:
  secret_key_base: 3ee1034dba6aa5ac102d96b0d6f67682b13b082627611c8d2b3b697f5d151edf16727a843dccc8fea32a68cff28698bf4d215942ff11a71c4dd38b0f0b973f79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
